name: Setup Node.js
description: Setup Node.js and install dependencies

runs:
  using: composite
  steps:
    - name: Setup Node.js
      id: setup_nodejs
      uses: actions/setup-node@v4.0.3
      with:
        node-version-file: '.tool-versions'
    - uses: actions/cache@v4.0.2
      id: cache
      with:
        path: node_modules
        key: ${{ runner.arch }}-${{ runner.os }}-node-${{ steps.setup_nodejs.outputs.node-version }}-npm-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm ci
      shell: bash
