name: CI

on: [pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  TZ: 'Asia/Tokyo'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.1
        with:
          fetch-depth: 0

      - name: Setup Node.js and install dependencies
        uses: ./.github/actions/setupNode

      - name: Run linter 👀
        run: npm run lint

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.1
        with:
          fetch-depth: 0

      - name: Setup Node.js and install dependencies
        uses: ./.github/actions/setupNode

      - name: Run build 👀
        run: npm run build
